EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"

LLM_MODEL = "gemini-2.5-flash"

SKILL_MATCH_THRESHOLD = 0.70

TOP_N_KEYWORDS = 25
NR_CANDIDATES = 40

REQUIRED_SKILL_WEIGHT = 0.80
PREFERRED_SKILL_WEIGHT = 0.20