EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"

SKILL_MATCH_THRESHOLD = 0.70

SEMANTIC_WEIGHT = 0.40
SKILL_WEIGHT = 0.25
CRITICAL_SKILL_WEIGHT = 0.20
KEYWORD_WEIGHT = 0.10

LLM_MODEL = "gemini-2.5-flash"